# Generated by Django 5.0.4 on 2024-04-15 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_day_event_itinerary_day_itinerary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='itinerary',
        ),
        migrations.RemoveField(
            model_name='event',
            name='day',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='place',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='created',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='location',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='itinerary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.itinerary'),
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
