# Generated by Django 5.0.4 on 2024-04-15 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_day_itinerary_remove_event_day_delete_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='itinerary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.itinerary'),
        ),
    ]
